'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { UserPlus, Trash2 } from 'lucide-react';
const inp='w-full rounded-btn bg-white px-3 py-2 text-[13px] outline-none ring-1 ring-inset ring-ink-200 focus:ring-brand-500';
export type Team={id:string;nama:string;email:string;username:string|null;aktif:boolean;totpEnabled:boolean;lastLoginAt:string|null};
export function TeamsClient({teams,currentId}:{teams:Team[];currentId:string}){
 const [f,setF]=useState({nama:'',email:'',username:'',password:''});const [err,setErr]=useState('');const router=useRouter();
 async function tambah(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/admin/teams',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});const d=await r.json();if(!d.ok){setErr(d.pesan);return;}setF({nama:'',email:'',username:'',password:''});router.refresh();}
 async function toggle(t:Team){const r=await fetch(`/api/admin/teams/${t.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({aktif:!t.aktif})});if(!r.ok)setErr((await r.json()).pesan);else router.refresh();}
 async function hapus(t:Team){if(!confirm(`Hapus akun ${t.nama}?`))return;const r=await fetch(`/api/admin/teams/${t.id}`,{method:'DELETE'});if(!r.ok)setErr((await r.json()).pesan);else router.refresh();}
 return <div className="space-y-4"><form onSubmit={tambah} className="rounded-card border border-ink-200 bg-white p-5 shadow-soft"><h2 className="text-[14px] font-semibold">Tambah Anggota Admin</h2><div className="mt-3 grid gap-2 sm:grid-cols-2"><input required className={inp} placeholder="Nama" value={f.nama} onChange={e=>setF({...f,nama:e.target.value})}/><input required type="email" className={inp} placeholder="Email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input className={inp} placeholder="Username" value={f.username} onChange={e=>setF({...f,username:e.target.value})}/><input required type="password" className={inp} placeholder="Password awal (min. 12)" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/></div><button className="mt-3 inline-flex items-center gap-2 rounded-btn bg-brand-600 px-3 py-2 text-[13px] font-semibold text-white"><UserPlus size={15}/>Tambah Admin</button></form>
 <section className="overflow-hidden rounded-card border border-ink-200 bg-white shadow-soft"><div className="border-b border-ink-200 px-4 py-3 text-[13px] font-semibold">Anggota ({teams.length})</div><ul className="divide-y divide-ink-200">{teams.map(t=><li key={t.id} className="flex items-center gap-3 px-4 py-3"><span className={`h-2 w-2 rounded-full ${t.aktif?'bg-ok-500':'bg-ink-400'}`}/><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-medium">{t.nama}{t.id===currentId?' (kamu)':''}</p><p className="truncate text-[11px] text-ink-400">{t.username?`@${t.username} · `:''}{t.email} · 2FA {t.totpEnabled?'aktif':'mati'}</p></div>{t.id!==currentId&&<><button onClick={()=>toggle(t)} className="rounded-chip px-2 py-1 text-[11px] font-semibold hover:bg-ink-100">{t.aktif?'Nonaktifkan':'Aktifkan'}</button><button onClick={()=>hapus(t)} aria-label={`Hapus ${t.nama}`} className="grid h-7 w-7 place-items-center rounded-chip text-ink-400 hover:bg-bad-50 hover:text-bad-700"><Trash2 size={14}/></button></>}</li>)}</ul></section>{err&&<p className="text-[12px] text-bad-700">{err}</p>}</div>;
}
